#!/usr/bin/env python3
"""
FlowWrapper: check-email
Original: workflows/available/community/check-email
Generated by: flowwrapper clawflow
Default model: ollama/qwen2.5:7b

REQUIRES: offlineimap or local Maildir at MAILDIR_PATH env var

This is a reference example showing what flowwrapper generates.
The actual generated script is tailored to the target workflow.
"""
import json
import os
import sys
import mailbox
import email
from datetime import datetime, timezone
from pathlib import Path
from litellm import completion
from dotenv import load_dotenv

load_dotenv()

MODEL = os.getenv("FLOWWRAPPER_MODEL", "ollama/qwen2.5:7b")
MAILDIR_PATH = os.getenv("MAILDIR_PATH", str(Path.home() / "Maildir" / "INBOX"))
MAX_EMAILS = int(os.getenv("FLOWWRAPPER_MAX_EMAILS", "30"))


# ---------------------------------------------------------------------------
# Core JSON caller — strict, no free text
# ---------------------------------------------------------------------------

def call(system: str, user: str, schema: dict) -> dict:
    """Single LiteLLM call. Always returns parsed JSON matching schema."""
    schema_str = json.dumps(schema, indent=2)
    prompt = (
        f"{system}\n\n"
        f"Respond ONLY with valid JSON matching this schema:\n{schema_str}\n"
        f"No explanation. No markdown fences. Pure JSON."
    )
    response = completion(
        model=MODEL,
        messages=[
            {"role": "system", "content": prompt},
            {"role": "user", "content": user},
        ],
        temperature=0.1,
    )
    raw = response.choices[0].message.content.strip()
    if raw.startswith("```"):
        raw = "\n".join(raw.split("\n")[1:])
        if raw.endswith("```"):
            raw = raw[: raw.rfind("```")]
    try:
        return json.loads(raw.strip())
    except json.JSONDecodeError as e:
        print(f"[flowwrapper] JSON parse error: {e}\nRaw:\n{raw}", file=sys.stderr)
        sys.exit(1)


# ---------------------------------------------------------------------------
# Step 1: Read emails from Maildir (side effect — no model call)
# ---------------------------------------------------------------------------

def step_read_maildir() -> list[dict]:
    """Read recent unread emails from local Maildir. No model call."""
    mdir = mailbox.Maildir(MAILDIR_PATH, factory=None)
    emails = []
    for key, msg in mdir.items():
        if "S" in msg.get_flags():  # S = Seen
            continue
        # Extract only the fields the model needs — never dump full body
        sender = msg.get("From", "")
        subject = msg.get("Subject", "")
        date_str = msg.get("Date", "")
        # Body snippet: first 300 chars of text/plain part only
        snippet = ""
        if msg.is_multipart():
            for part in msg.walk():
                if part.get_content_type() == "text/plain":
                    snippet = part.get_payload(decode=True).decode(errors="replace")[:300]
                    break
        else:
            snippet = msg.get_payload(decode=True).decode(errors="replace")[:300]

        emails.append({
            "key": key,
            "from": sender,
            "subject": subject,
            "date": date_str,
            "snippet": snippet,
        })
        if len(emails) >= MAX_EMAILS:
            break
    return emails


# ---------------------------------------------------------------------------
# Step 2: Classify each email (model call — atomic binary decision)
# ---------------------------------------------------------------------------

CLASSIFY_SCHEMA = {
    "category": "string",   # "action_required" | "newsletter" | "notification" | "noise"
    "priority": "string",   # "high" | "normal" | "low"
    "reason": "string",     # one sentence, max 80 chars
}

def step_classify(email_data: dict) -> dict:
    """Classify a single email into a category. One model call per email."""
    return call(
        system=(
            "You are an email classifier. Classify the given email into exactly one category:\n"
            "- action_required: needs a human response or decision\n"
            "- newsletter: marketing, digest, subscription content\n"
            "- notification: automated system/service notification\n"
            "- noise: spam, irrelevant, or unclear\n"
            "Base your decision ONLY on From, Subject, and the snippet. Be strict."
        ),
        user=json.dumps({
            "from": email_data["from"],
            "subject": email_data["subject"],
            "snippet": email_data["snippet"],
        }),
        schema=CLASSIFY_SCHEMA,
    )


# ---------------------------------------------------------------------------
# Step 3: Summarize action_required emails (model call)
# ---------------------------------------------------------------------------

SUMMARIZE_SCHEMA = {
    "summary": "string",    # one sentence describing what action is needed
    "deadline": "string",   # ISO date string or "none"
}

def step_summarize(email_data: dict) -> dict:
    """Summarize what action is needed. Only called for action_required emails."""
    return call(
        system=(
            "You are an email assistant. Given an email, output a one-sentence summary "
            "of what action the recipient needs to take, and a deadline if mentioned. "
            "If no deadline is mentioned, use 'none'."
        ),
        user=json.dumps({
            "from": email_data["from"],
            "subject": email_data["subject"],
            "snippet": email_data["snippet"],
        }),
        schema=SUMMARIZE_SCHEMA,
    )


# ---------------------------------------------------------------------------
# Step 4: Print report (side effect — no model call)
# ---------------------------------------------------------------------------

def side_effect_report(results: list[dict]) -> None:
    """Print structured summary to stdout. No model call."""
    action = [r for r in results if r["category"] == "action_required"]
    newsletters = [r for r in results if r["category"] == "newsletter"]
    notifications = [r for r in results if r["category"] == "notification"]
    noise = [r for r in results if r["category"] == "noise"]

    print(f"\n📧 Email Summary — {datetime.now(timezone.utc).strftime('%Y-%m-%d %H:%M UTC')}")
    print(f"   Scanned: {len(results)} unread")
    print(f"   Action required: {len(action)} | Newsletter: {len(newsletters)} | Noise: {len(noise)}\n")

    if action:
        print("🔴 Action Required:")
        for r in action:
            deadline = f" [by {r.get('deadline')}]" if r.get("deadline") != "none" else ""
            print(f"   • {r['subject'][:60]} — {r.get('summary', '')}{deadline}")

    if newsletters:
        print(f"\n📰 Newsletters ({len(newsletters)}): " + ", ".join(r["from"][:30] for r in newsletters[:5]))

    print()


# ---------------------------------------------------------------------------
# Main pipeline
# ---------------------------------------------------------------------------

def main() -> None:
    # 1. Read local Maildir
    emails = step_read_maildir()
    if not emails:
        print(json.dumps({"status": "ok", "summary": "No unread emails."}))
        return

    # 2. Classify each email
    results = []
    for em in emails:
        classification = step_classify(em)
        record = {**em, **classification}

        # 3. Summarize if action required
        if classification["category"] == "action_required":
            summary = step_summarize(em)
            record.update(summary)

        results.append(record)

    # 4. Report
    side_effect_report(results)

    # Machine-readable output for chaining
    print(json.dumps({
        "status": "ok",
        "total": len(results),
        "action_required": len([r for r in results if r["category"] == "action_required"]),
        "model": MODEL,
    }))


if __name__ == "__main__":
    main()
